name = "shine"
version = "1.0.0"
description = "A TUI library for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "gleemers", repo = "shine" }
# links = [{ title = "Website", href = "" }] # planned for future

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
